# Dependencies
gems:                [jekyll-paginate]
markdown:            redcarpet
highlighter:         pygments		

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Simply Statistics
tagline:             '<img src="https://raw.githubusercontent.com/simplystats/simplystats.github.io/master/public/sslogo.png" </img>'
description:         ''
url:                 http://simplystats.github.io
baseurl:             ''
paginate:            10

