# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Simply Statistics
tagline:             'A blog by <a href="https://twitter.com/rafalab">Rafa Irizarry<a>,<a href="https://twitter.com/rdpeng">Roger Peng<a>, and <a href="https://twitter.com/jtleek">Jeff Leek<a>'
description:         'A blog by <a href="https://twitter.com/rafalab">Rafa Irizarry<a>,<a href="https://twitter.com/rdpeng">Roger Peng<a>, and <a href="https://twitter.com/jtleek">Jeff Leek<a>'
url:                 http://simplystats.github.io
baseurl:             ''
paginate:            10

